export const articles_mock = {
  uri: "nyt://article/7786ae91-819b-52ed-b219-a4c265f0efa7",
  url: "https://example.com",
  id: 100000009586898,
  asset_id: 100000009586898,
  source: "Test Source",
  published_date: "2024-07-31",
  updated: "2024-07-31 09:00:02",
  section: "Style",
  subsection: "",
  nytdsection: "style",
  adx_keywords: "Customs, Etiquette and Manners",
  column: null,
  byline: "Test Author",
  type: "Article",
  title: "Test Article",
  abstract: "This is a test abstract.",
  des_facet: ["Customs, Etiquette and Manners"],
  org_facet: [],
  per_facet: [],
  geo_facet: [],
  media: [
    {
      type: "image",
      subtype: "photo",
      caption: "Test Caption",
      copyright: "Miguel Porlan",
      approved_for_syndication: 1,
      "media-metadata": [
        {
          url: "https://static01.nyt.com/images/2021/06/20/fashion/socialqs-2021-artwork/socialqs-2021-artwork-thumbStandard-v2.jpg",
          format: "Standard Thumbnail",
          height: 75,
          width: 75,
        },
        {
          url: "https://example.com/image.jpg",
          format: "mediumThreeByTwo210",
          height: 140,
          width: 210,
        },
        {
          url: "https://static01.nyt.com/images/2021/06/20/fashion/socialqs-2021-artwork/socialqs-2021-artwork-mediumThreeByTwo440.jpg",
          format: "mediumThreeByTwo440",
          height: 293,
          width: 440,
        },
      ],
    },
  ],
  eta_id: 0,
};
